[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["RyanMichaud <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
getch = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
